# Generated by Django 4.0.6 on 2026-03-14 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='invite_code',
            field=models.CharField(editable=False, help_text='Share this code to invite members. Never searchable.', max_length=8, unique=True),
        ),
    ]
