# Generated by Django 5.2.12 on 2026-03-15 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_invite_code_charfield"),
    ]

    operations = [
        migrations.AddField(
            model_name="redemption",
            name="deadline",
            field=models.DateField(
                blank=True,
                help_text="Date by which the partner should fulfill this reward.",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="ImportantDate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("note", models.TextField(blank=True)),
                ("date", models.DateField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("anniversary", "Anniversary"),
                            ("birthday", "Birthday"),
                            ("special", "Special Moment"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                (
                    "is_recurring",
                    models.BooleanField(
                        default=True, help_text="If True, the date repeats every year."
                    ),
                ),
                (
                    "reminder_days",
                    models.PositiveIntegerField(
                        default=7,
                        help_text="Show a reminder this many days before the date.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="important_dates",
                        to="core.profile",
                    ),
                ),
                (
                    "house",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="important_dates",
                        to="core.house",
                    ),
                ),
            ],
        ),
    ]
